@baseUrl = http://localhost:8001

### 1. Registrar administrador
POST {{baseUrl}}/api/registro/administrador
Content-Type: application/json

{
    "nombre": "Admin Funciona",
    "correo": "admin3@taller.com",
    "contrasena": "clave123"
}

### 2. Registrar tecnico
POST {{baseUrl}}/api/registro/tecnico
Content-Type: application/json

{
    "nombre": "Santiago Gomez",
    "correo": "santiago2@taller.com.",
    "contrasena": "clave123",
    "documento": "12345678",
    "especialidad": "Hardware y portatiles",
    "telefono": "3109876543"
}

### 3. Login correcto
# @name login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "correo": "admin3@taller.com",
    "contrasena": "clave123"
}

### 4. Login incorrecto (contraseña mala)
POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "correo": "santiago2@taller.com",
    "contrasena": "claveincorrecta"
}

### 5. Registrar cliente SIN token 
POST {{baseUrl}}/api/clientes
Content-Type: application/json

{
    "nombre_completo": "Carla Perez",
    "documento": "12352155",
    "telefono": "3204104901",
    "correo": "carla@email.com"
}

### 6. Registrar cliente CON token
# Copia el "token" que te devolvió la petición 3 (login) y pégalo abajo
POST {{baseUrl}}/api/clientes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwicm9sIjoiQURNSU5JU1RSQURPUiIsImVtYWlsIjoiYWRtaW4zQHRhbGxlci5jb20iLCJub21icmUiOiJBZG1pbiBGdW5jaW9uYSIsImp0aSI6IjJmMmMwN2EzLWY1MGQtNDkwMi1iZDJmLTk2OGY1ZDRkNDQzMiIsImV4cCI6MTc4OTUwOTAzM30.NMsVP8h0F7ifbE5aqM9Wr3Dz3ARn8SSjen8XyikPn-Q

{
    "nombre_completo": "Juan Gomez",
    "documento": "105293903",
    "telefono": "3001234567",
    "correo": "juangomez@email.com"
}

### 7. Logout
POST {{baseUrl}}/api/logout
###
POST  http://localhost:8001/tecnicos

{
  "usuario_id":1 ,
  "documento": "454545",
  "especialidad": "Hardware y portátiles",
  "telefono": "3109876543",
  "estado": "ACTIVO"
}

###
POST http://localhost:8001/equipos

{
  "cliente_id": 1,
  "tipo_equipo": "Computador portátil",
  "marca": "Lenovo",
  "modelo": "ThinkPad E14",
  "numero_serie": "SN-LEN-002",
  "descripcion_problema": "No enciende"
}
###
POST http://localhost:8001/ordenes

{
  "cliente_id": 1,
  "equipo_id": 1,
  "tecnico_id": 1,
  "descripcion_problema": "No enciende",
  "observaciones": "Cliente deja cargador",
  "valor_estimado": 150000,
  "valor_final": 0
}

###
PUT http://localhost:8001/ordenes/1

{
  "tecnico_id": 1,
  "descripcion_problema": "Falla de fuente confirmada",
  "observaciones": "Cotizar repuesto",
  "valor_estimado": 180000,
  "valor_final": 0
}